version: '2'
volumes:
  images:
services:
  frontend:
    restart: always
    image: balenablocks/browser:raspberrypi3-64
    privileged: true
    network_mode: host
    depends_on:
      - ripper
  ripper:
    build: ./ripper
    privileged: true
    devices:
      - '/dev/sr0:/dev/sr0'
      - '/dev/cdrom:/dev/cdrom'
      - '/dev/dvd:/dev/dvd'
    volumes:
      - 'images:/data'